### PR TITLE
Deletion of constants deletes more lines than expected

### LINKED ISSUE #50: preg_match_all fails with concatenated string
## Bug Report

- [ x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [ x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

A string in wp-config.php like this:

```php
define( 'WP_HOME', 'https://'.$_SERVER['HTTP_HOST'] );
```

Is not properly match in parse_wp_config() and ends up swallowing additional line(s).

The quick fix (for me) was to change to:

```php
define( 'WP_HOME', "https://{$_SERVER['HTTP_HOST']}" );
```

But that doesn't change things in the wild.

You can see this by pasting the line in the [regex101](https://regex101.com/r/6AeNGP/4) before the `/* That's all, stop editing! Happy blogging. */` line.

### PR DESCRIPTION
**Pull request by shreya0204**
Fixes #50 
Fixes wp-cli/config-command#101

This pull request addresses the bug where using `wp config delete` to remove a constant from `wp-config.php` that includes concatenated functions or complex strings results in the incorrect deletion of more than just the targeted constant.

### Current Behavior

Currently, when deleting a constant that includes concatenated functions or special characters, the regex used in the deletion function does not properly isolate the constant. This results in deleting additional lines or even other constants. For example:

```php
define( 'WP_DEBUG', false );
define( 'USER_PATH', '/var/www/' . get_current_user() );
define( 'THIS_AND', md5( 'that' ) );
if ( isset( $_SERVER['HTTP_X_FORWARDED_PROTO'] ) && 'https' === $_SERVER['HTTP_X_FORWARDED_PROTO'] ) {
	$_SERVER['HTTPS'] = 'on';
}
define( 'DISABLE_WP_CRON', true );
```

Running `wp config delete USER_PATH` would improperly affect adjacent lines.

### Steps to Replicate

1. Have a `wp-config.php` file with a constant definition concatenating a function.
2. Run `wp config delete USER_PATH`.

### Expected Outcome

Only the line defining `USER_PATH` should be removed, leaving all other settings and definitions intact.

### Issue Details

The issue stemmed from the regex pattern used in the removal function, which failed to correctly identify the boundaries of the constant definition when it involved concatenated functions or complex string values.

### Proposed Solution

This PR introduces a revised regex pattern that more accurately matches and isolates `define` statements, even when they contain complex string values or are among multiple statements on a single line. The new regex handles variations in whitespace and formatting, ensuring that only the specific constant is removed.

### CODE REVIEW

File: src/WPConfigTransformer.php [hunk 1]
```diff
@@ -226,8 +226,21 @@ public function remove( $type, $name ) {
...
+				"/\bdefine\s*\(\s*['\"]%s['\"]\s*,\s*(('[^']*'|\"[^\"]*\")|\s*(?:[\s\S]*?))\s*\)\s*;\s*/mi",
+				preg_quote( $name, '/' )
+			);
+		} elseif ( 'variable' === $type ) {
+			$pattern = sprintf(
+				'/^\s*\$%s\s*=\s*[\s\S]*?;\s*$/mi',
+				preg_quote( $name, '/' )
+			);
+		} else {
+			return false;
```
Comment (ernilambar) [inline src/WPConfigTransformer.php:240]: This `return false` seems redundant to me. If not valid type then it will return false earlier in 226. Thoughts?

**Comment by ernilambar** [comment]
@shreya0204 Thanks for the PR. Could you please add some tests also?

File: src/WPConfigTransformer.php (hunk 1 above)
Comment (shreya0204) [reply src/WPConfigTransformer.php:240]: Yes, you're right. If the type isn't 'constant' or 'variable', the function won't go past the initial check at line 226. Handling 'constant' in the `if` condition and 'variable' in the `else` condition should cover all our needs without extra checks.

Does this sound good to you?

**Comment by shreya0204** [comment]
> @shreya0204 Thanks for the PR. Could you please add some tests also?

Can you guide me on how to add?

**Comment by ernilambar** [comment]
> > @shreya0204 Thanks for the PR. Could you please add some tests also?
> 
> Can you guide me on how to add for this particular fix?

Tests regarding add/remove config is in this file - https://github.com/wp-cli/wp-config-transformer/blob/main/tests/AddRemoveTest.php This could provide idea for the test implementation. Here are the steps to run test https://github.com/wp-cli/wp-config-transformer?tab=readme-ov-file#testing

**Comment by shreya0204** [comment]
@ernilambar I've implemented a new test to ensure the safe removal of constants that have concatenated strings as their values. This test specifically checks that only the targeted constant is removed, and that no additional lines or constants are inadvertently affected during the process.

**Review by ernilambar — APPROVED** [review]
